# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jianyu/Sharpvpn

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jianyu/Sharpvpn

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jianyu/Sharpvpn/CMakeFiles /home/jianyu/Sharpvpn/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jianyu/Sharpvpn/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Sharpvpn

# Build rule for target.
Sharpvpn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sharpvpn
.PHONY : Sharpvpn

# fast build rule for target.
Sharpvpn/fast:
	$(MAKE) -f CMakeFiles/Sharpvpn.dir/build.make CMakeFiles/Sharpvpn.dir/build
.PHONY : Sharpvpn/fast

#=============================================================================
# Target rules for targets named TcpClient

# Build rule for target.
TcpClient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TcpClient
.PHONY : TcpClient

# fast build rule for target.
TcpClient/fast:
	$(MAKE) -f CMakeFiles/TcpClient.dir/build.make CMakeFiles/TcpClient.dir/build
.PHONY : TcpClient/fast

#=============================================================================
# Target rules for targets named TcpServer

# Build rule for target.
TcpServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TcpServer
.PHONY : TcpServer

# fast build rule for target.
TcpServer/fast:
	$(MAKE) -f CMakeFiles/TcpServer.dir/build.make CMakeFiles/TcpServer.dir/build
.PHONY : TcpServer/fast

src/DaemonRuntime.o: src/DaemonRuntime.cpp.o
.PHONY : src/DaemonRuntime.o

# target to build an object file
src/DaemonRuntime.cpp.o:
	$(MAKE) -f CMakeFiles/Sharpvpn.dir/build.make CMakeFiles/Sharpvpn.dir/src/DaemonRuntime.cpp.o
.PHONY : src/DaemonRuntime.cpp.o

src/DaemonRuntime.i: src/DaemonRuntime.cpp.i
.PHONY : src/DaemonRuntime.i

# target to preprocess a source file
src/DaemonRuntime.cpp.i:
	$(MAKE) -f CMakeFiles/Sharpvpn.dir/build.make CMakeFiles/Sharpvpn.dir/src/DaemonRuntime.cpp.i
.PHONY : src/DaemonRuntime.cpp.i

src/DaemonRuntime.s: src/DaemonRuntime.cpp.s
.PHONY : src/DaemonRuntime.s

# target to generate assembly for a file
src/DaemonRuntime.cpp.s:
	$(MAKE) -f CMakeFiles/Sharpvpn.dir/build.make CMakeFiles/Sharpvpn.dir/src/DaemonRuntime.cpp.s
.PHONY : src/DaemonRuntime.cpp.s

src/SharpCrypto.o: src/SharpCrypto.cpp.o
.PHONY : src/SharpCrypto.o

# target to build an object file
src/SharpCrypto.cpp.o:
	$(MAKE) -f CMakeFiles/Sharpvpn.dir/build.make CMakeFiles/Sharpvpn.dir/src/SharpCrypto.cpp.o
.PHONY : src/SharpCrypto.cpp.o

src/SharpCrypto.i: src/SharpCrypto.cpp.i
.PHONY : src/SharpCrypto.i

# target to preprocess a source file
src/SharpCrypto.cpp.i:
	$(MAKE) -f CMakeFiles/Sharpvpn.dir/build.make CMakeFiles/Sharpvpn.dir/src/SharpCrypto.cpp.i
.PHONY : src/SharpCrypto.cpp.i

src/SharpCrypto.s: src/SharpCrypto.cpp.s
.PHONY : src/SharpCrypto.s

# target to generate assembly for a file
src/SharpCrypto.cpp.s:
	$(MAKE) -f CMakeFiles/Sharpvpn.dir/build.make CMakeFiles/Sharpvpn.dir/src/SharpCrypto.cpp.s
.PHONY : src/SharpCrypto.cpp.s

src/SharpPackageParser.o: src/SharpPackageParser.cpp.o
.PHONY : src/SharpPackageParser.o

# target to build an object file
src/SharpPackageParser.cpp.o:
	$(MAKE) -f CMakeFiles/Sharpvpn.dir/build.make CMakeFiles/Sharpvpn.dir/src/SharpPackageParser.cpp.o
.PHONY : src/SharpPackageParser.cpp.o

src/SharpPackageParser.i: src/SharpPackageParser.cpp.i
.PHONY : src/SharpPackageParser.i

# target to preprocess a source file
src/SharpPackageParser.cpp.i:
	$(MAKE) -f CMakeFiles/Sharpvpn.dir/build.make CMakeFiles/Sharpvpn.dir/src/SharpPackageParser.cpp.i
.PHONY : src/SharpPackageParser.cpp.i

src/SharpPackageParser.s: src/SharpPackageParser.cpp.s
.PHONY : src/SharpPackageParser.s

# target to generate assembly for a file
src/SharpPackageParser.cpp.s:
	$(MAKE) -f CMakeFiles/Sharpvpn.dir/build.make CMakeFiles/Sharpvpn.dir/src/SharpPackageParser.cpp.s
.PHONY : src/SharpPackageParser.cpp.s

src/SharpTunnel.o: src/SharpTunnel.cpp.o
.PHONY : src/SharpTunnel.o

# target to build an object file
src/SharpTunnel.cpp.o:
	$(MAKE) -f CMakeFiles/Sharpvpn.dir/build.make CMakeFiles/Sharpvpn.dir/src/SharpTunnel.cpp.o
.PHONY : src/SharpTunnel.cpp.o

src/SharpTunnel.i: src/SharpTunnel.cpp.i
.PHONY : src/SharpTunnel.i

# target to preprocess a source file
src/SharpTunnel.cpp.i:
	$(MAKE) -f CMakeFiles/Sharpvpn.dir/build.make CMakeFiles/Sharpvpn.dir/src/SharpTunnel.cpp.i
.PHONY : src/SharpTunnel.cpp.i

src/SharpTunnel.s: src/SharpTunnel.cpp.s
.PHONY : src/SharpTunnel.s

# target to generate assembly for a file
src/SharpTunnel.cpp.s:
	$(MAKE) -f CMakeFiles/Sharpvpn.dir/build.make CMakeFiles/Sharpvpn.dir/src/SharpTunnel.cpp.s
.PHONY : src/SharpTunnel.cpp.s

src/SharpVpn.o: src/SharpVpn.cpp.o
.PHONY : src/SharpVpn.o

# target to build an object file
src/SharpVpn.cpp.o:
	$(MAKE) -f CMakeFiles/Sharpvpn.dir/build.make CMakeFiles/Sharpvpn.dir/src/SharpVpn.cpp.o
.PHONY : src/SharpVpn.cpp.o

src/SharpVpn.i: src/SharpVpn.cpp.i
.PHONY : src/SharpVpn.i

# target to preprocess a source file
src/SharpVpn.cpp.i:
	$(MAKE) -f CMakeFiles/Sharpvpn.dir/build.make CMakeFiles/Sharpvpn.dir/src/SharpVpn.cpp.i
.PHONY : src/SharpVpn.cpp.i

src/SharpVpn.s: src/SharpVpn.cpp.s
.PHONY : src/SharpVpn.s

# target to generate assembly for a file
src/SharpVpn.cpp.s:
	$(MAKE) -f CMakeFiles/Sharpvpn.dir/build.make CMakeFiles/Sharpvpn.dir/src/SharpVpn.cpp.s
.PHONY : src/SharpVpn.cpp.s

src/TcpSocket.o: src/TcpSocket.cpp.o
.PHONY : src/TcpSocket.o

# target to build an object file
src/TcpSocket.cpp.o:
	$(MAKE) -f CMakeFiles/Sharpvpn.dir/build.make CMakeFiles/Sharpvpn.dir/src/TcpSocket.cpp.o
	$(MAKE) -f CMakeFiles/TcpClient.dir/build.make CMakeFiles/TcpClient.dir/src/TcpSocket.cpp.o
	$(MAKE) -f CMakeFiles/TcpServer.dir/build.make CMakeFiles/TcpServer.dir/src/TcpSocket.cpp.o
.PHONY : src/TcpSocket.cpp.o

src/TcpSocket.i: src/TcpSocket.cpp.i
.PHONY : src/TcpSocket.i

# target to preprocess a source file
src/TcpSocket.cpp.i:
	$(MAKE) -f CMakeFiles/Sharpvpn.dir/build.make CMakeFiles/Sharpvpn.dir/src/TcpSocket.cpp.i
	$(MAKE) -f CMakeFiles/TcpClient.dir/build.make CMakeFiles/TcpClient.dir/src/TcpSocket.cpp.i
	$(MAKE) -f CMakeFiles/TcpServer.dir/build.make CMakeFiles/TcpServer.dir/src/TcpSocket.cpp.i
.PHONY : src/TcpSocket.cpp.i

src/TcpSocket.s: src/TcpSocket.cpp.s
.PHONY : src/TcpSocket.s

# target to generate assembly for a file
src/TcpSocket.cpp.s:
	$(MAKE) -f CMakeFiles/Sharpvpn.dir/build.make CMakeFiles/Sharpvpn.dir/src/TcpSocket.cpp.s
	$(MAKE) -f CMakeFiles/TcpClient.dir/build.make CMakeFiles/TcpClient.dir/src/TcpSocket.cpp.s
	$(MAKE) -f CMakeFiles/TcpServer.dir/build.make CMakeFiles/TcpServer.dir/src/TcpSocket.cpp.s
.PHONY : src/TcpSocket.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Sharpvpn.dir/build.make CMakeFiles/Sharpvpn.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Sharpvpn.dir/build.make CMakeFiles/Sharpvpn.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Sharpvpn.dir/build.make CMakeFiles/Sharpvpn.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

test/test_tcp.o: test/test_tcp.cpp.o
.PHONY : test/test_tcp.o

# target to build an object file
test/test_tcp.cpp.o:
	$(MAKE) -f CMakeFiles/TcpClient.dir/build.make CMakeFiles/TcpClient.dir/test/test_tcp.cpp.o
.PHONY : test/test_tcp.cpp.o

test/test_tcp.i: test/test_tcp.cpp.i
.PHONY : test/test_tcp.i

# target to preprocess a source file
test/test_tcp.cpp.i:
	$(MAKE) -f CMakeFiles/TcpClient.dir/build.make CMakeFiles/TcpClient.dir/test/test_tcp.cpp.i
.PHONY : test/test_tcp.cpp.i

test/test_tcp.s: test/test_tcp.cpp.s
.PHONY : test/test_tcp.s

# target to generate assembly for a file
test/test_tcp.cpp.s:
	$(MAKE) -f CMakeFiles/TcpClient.dir/build.make CMakeFiles/TcpClient.dir/test/test_tcp.cpp.s
.PHONY : test/test_tcp.cpp.s

test/test_tcp_server.o: test/test_tcp_server.cpp.o
.PHONY : test/test_tcp_server.o

# target to build an object file
test/test_tcp_server.cpp.o:
	$(MAKE) -f CMakeFiles/TcpServer.dir/build.make CMakeFiles/TcpServer.dir/test/test_tcp_server.cpp.o
.PHONY : test/test_tcp_server.cpp.o

test/test_tcp_server.i: test/test_tcp_server.cpp.i
.PHONY : test/test_tcp_server.i

# target to preprocess a source file
test/test_tcp_server.cpp.i:
	$(MAKE) -f CMakeFiles/TcpServer.dir/build.make CMakeFiles/TcpServer.dir/test/test_tcp_server.cpp.i
.PHONY : test/test_tcp_server.cpp.i

test/test_tcp_server.s: test/test_tcp_server.cpp.s
.PHONY : test/test_tcp_server.s

# target to generate assembly for a file
test/test_tcp_server.cpp.s:
	$(MAKE) -f CMakeFiles/TcpServer.dir/build.make CMakeFiles/TcpServer.dir/test/test_tcp_server.cpp.s
.PHONY : test/test_tcp_server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Sharpvpn"
	@echo "... TcpClient"
	@echo "... TcpServer"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... src/DaemonRuntime.o"
	@echo "... src/DaemonRuntime.i"
	@echo "... src/DaemonRuntime.s"
	@echo "... src/SharpCrypto.o"
	@echo "... src/SharpCrypto.i"
	@echo "... src/SharpCrypto.s"
	@echo "... src/SharpPackageParser.o"
	@echo "... src/SharpPackageParser.i"
	@echo "... src/SharpPackageParser.s"
	@echo "... src/SharpTunnel.o"
	@echo "... src/SharpTunnel.i"
	@echo "... src/SharpTunnel.s"
	@echo "... src/SharpVpn.o"
	@echo "... src/SharpVpn.i"
	@echo "... src/SharpVpn.s"
	@echo "... src/TcpSocket.o"
	@echo "... src/TcpSocket.i"
	@echo "... src/TcpSocket.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... test/test_tcp.o"
	@echo "... test/test_tcp.i"
	@echo "... test/test_tcp.s"
	@echo "... test/test_tcp_server.o"
	@echo "... test/test_tcp_server.i"
	@echo "... test/test_tcp_server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

